version: '3'

services:
  database:
    image: mysql:8.0.21
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=SenhaMuitoSegura!123
    volumes:
      - database/:/docker-entrypoint-initdb.d
    platform: linux/x86_64

  api:
    build: ./backend
    container_name: api
    ports:
      - 3001:3001
    depends_on:
      - database
    environment:
      - PORT=3001
      - DB_USER=root
      - DB_PASS=SenhaMuitoSegura!123
      - DB_HOST=db
      - DB_NAME=KelDigitalBank
      - DB_PORT=3306
    volumes:
      - ./backend:/app-back

  web:
    build: ./frontend
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./backend:/app-front

