version: '3'

services:
  database:
    image: postgres
    container_name: db
    ports:
      - 3002:5432
    environment:
      - POSTGRES_PASSWORD=SenhaMuitoSegura!123
    restart: 'always'

  api:
    build: ./backend
    container_name: api
    ports:
      - 3001:3001
    depends_on:
      - database
    environment:
      - PORT=3001
      - DB_USER=postgres
      - DB_PASS=SenhaMuitoSegura!123
      - DB_HOST=db
      - DB_NAME=KelDigitalBank
      - DB_PORT=5432
    volumes:
      - ./backend:/app-back

  web:
    build: ./kel-digital
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./kel-digital:/app-front

